# services:
#   remnawave-node:
#     container_name: remnawave-node
#     hostname: remnawave-node
#     image: remnawave/node:latest
#     env_file:
#       - .env
#     network_mode: host

services:
  remnawave-node:
    container_name: remnawave-node
    hostname: remnawave-node
    build:
      context: .
      dockerfile: Dockerfile

    env_file:
      - .env
    ports:
      - 24000:24000
